### ISSUE TITLE
Moon is fucked

### ISSUE THREAD

**Issue by romanwarlock** [MUME/MMapper#304] opened 2023-03-24 18:27 UTC
Looks like 2 bloody morons Dain and Jahara marked as [A] made either MUME or Mmapper moon fucked.

**Comment by Kaspar-Metsa** [comment] 2023-04-02 15:34
If anyone ever works on fixing the Moon after: https://mume.org/news/game/2704.php

Please also take a look at some ideas for MMapper2 related to moon in this issue: https://github.com/MUME/MMapper/issues/280

**Comment by Kaspar-Metsa** [comment] 2023-04-14 08:06
The new moon cycle formula:
#define MOON_CYCLE_MINS = ((29 * MUD_HOURS_PER_DAY + 12) * MUD_MINS_PER_HOUR + 44)

It's the real world length of a synodic month rounded to minutes:
https://en.wikipedia.org/wiki/Lunar_month#Synodic_month

**Comment by nschimme** [comment] 2023-04-22 23:40
Duplicate of https://github.com/MUME/MMapper/issues/312

**Closed by nschimme** 2023-04-22 23:40 UTC
